CC=gcc
CFLAGS=-fopenmp -O2 -Wall -Wextra

exercise_three: exercise_three.c
	$(CC) $(CFLAGS) -o exercise_three exercise_three.c

matrix_vector: matrix_vector.c
	$(CC) $(CFLAGS) -o matrix_vector matrix_vector.c

locality: locality.c
	gcc -O2 -o locality locality.c
