CC=gcc
CFLAGS=-fopenmp -Wall -Wextra -O2

pi_par_loop_red: pi_par_loop_red.c
	$(CC) $(CFLAGS) -o pi_par_loop_red pi_par_loop_red.c

matmul_ikj: matmul_ikj.c
	$(CC) $(CFLAGS) -o matmul_ikj matmul_ikj.c

matmul_tiled: matmul_tiled.c
	$(CC) $(CFLAGS) -o matmul_tiled matmul_tiled.c

histogram: histogram.c
	$(CC) $(CFLAGS) -o histogram histogram.c

collatz: collatz.c
	$(CC) $(CFLAGS) -o collatz collatz.c
